using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using SquashClub.Web.Data;
using SquashClub.Web.Domain;
using SquashClub.Web.Services;
using Xunit;

namespace SquashClub.Tests;
public sealed class TestClock(DateTime now):TimeProvider { public DateTime Now=now; public override DateTimeOffset GetUtcNow()=>new(Now,TimeSpan.Zero); }
public sealed class Fixture:IAsyncDisposable
{
 readonly SqliteConnection connection=new("Data Source=:memory:"); public ClubDbContext Db=null!; public TestClock Clock=new(new DateTime(2026,8,26,12,0,0,DateTimeKind.Utc)); public ClubOptions Options=new(TimeZone:"UTC"); public Member Member=new(){Id=Guid.NewGuid(),UserName="a@club.test",Email="a@club.test",CreditBalanceUnits=1000}; public Member Opponent=new(){Id=Guid.NewGuid(),UserName="b@club.test",Email="b@club.test",CreditBalanceUnits=1000}; public Court Court=new(){Id=Guid.NewGuid(),Name="Court 1",LightingEnabled=true,Active=true};
 public async Task Init(bool active=true){await connection.OpenAsync();Db=new(new DbContextOptionsBuilder<ClubDbContext>().UseSqlite(connection).Options);await Db.Database.EnsureCreatedAsync();Db.Users.AddRange(Member,Opponent);var p=new MembershipProduct{Id=Guid.NewGuid(),Name="Adult",DurationDays=365};Db.MembershipProducts.Add(p);if(active)Db.Memberships.AddRange(new Membership{Id=Guid.NewGuid(),Member=Member,Product=p,StartsAtUtc=Clock.Now.AddDays(-1),EndsAtUtc=Clock.Now.AddDays(10)},new Membership{Id=Guid.NewGuid(),Member=Opponent,Product=p,StartsAtUtc=Clock.Now.AddDays(-1),EndsAtUtc=Clock.Now.AddDays(10)});Db.Courts.Add(Court);Db.OpeningHours.Add(new(){Id=Guid.NewGuid(),Day=Clock.Now.DayOfWeek,Opens=new(7,0),Closes=new(23,0)});Db.PeakPeriods.Add(new(){Id=Guid.NewGuid(),Day=Clock.Now.DayOfWeek,Starts=new(17,0),Ends=new(21,0),CostUnits=200});await Db.SaveChangesAsync();}
 public BookingService Booking()=>new(Db,new CreditService(Db,Clock),Options,Clock); public ValueTask DisposeAsync()=>Db.DisposeAsync();
}
public class BookingTests
{
 [Fact]public async Task Active_member_booking_debits_server_price_in_integer_units(){await using var f=new Fixture();await f.Init();var b=await f.Booking().BookAsync(new(f.Member.Id,f.Court.Id,f.Clock.Now.AddHours(1)));Assert.Equal(100,b.CreditCostUnits);Assert.Equal(900,f.Member.CreditBalanceUnits);Assert.Equal(-100,(await f.Db.CreditTransactions.SingleAsync()).Units);}
 [Fact]public async Task Inactive_member_cannot_book(){await using var f=new Fixture();await f.Init(false);var e=await Assert.ThrowsAsync<ClubRuleException>(()=>f.Booking().BookAsync(new(f.Member.Id,f.Court.Id,f.Clock.Now.AddHours(1))));Assert.Equal("MEMBERSHIP_INACTIVE",e.Code);}
 [Fact]public async Task Peak_limit_ignores_off_peak(){await using var f=new Fixture();await f.Init();await f.Booking().BookAsync(new(f.Member.Id,f.Court.Id,f.Clock.Now.AddHours(6)));var other=new Court{Id=Guid.NewGuid(),Name="Court 2",Active=true};f.Db.Courts.Add(other);await f.Db.SaveChangesAsync();var e=await Assert.ThrowsAsync<ClubRuleException>(()=>f.Booking().BookAsync(new(f.Member.Id,other.Id,f.Clock.Now.AddHours(7))));Assert.Equal("PEAK_LIMIT",e.Code);}
 [Fact]public async Task Split_requires_approval_and_refunds_actual_payers(){await using var f=new Fixture();await f.Init();var b=await f.Booking().BookAsync(new(f.Member.Id,f.Court.Id,f.Clock.Now.AddHours(4),f.Opponent.Id,PaymentMode.Split));Assert.Equal(950,f.Member.CreditBalanceUnits);Assert.Equal(1000,f.Opponent.CreditBalanceUnits);await f.Booking().ApproveSplitAsync(b.Id,f.Opponent.Id);Assert.Equal(950,f.Opponent.CreditBalanceUnits);await f.Booking().CancelAsync(b.Id,f.Member.Id);Assert.Equal(1000,f.Member.CreditBalanceUnits);Assert.Equal(1000,f.Opponent.CreditBalanceUnits);Assert.Equal(2,await f.Db.CreditTransactions.CountAsync(x=>x.Type==CreditTransactionType.CancellationRefund));}
 [Fact]public async Task Duplicate_split_approval_is_idempotent(){await using var f=new Fixture();await f.Init();var b=await f.Booking().BookAsync(new(f.Member.Id,f.Court.Id,f.Clock.Now.AddHours(4),f.Opponent.Id,PaymentMode.Split));await f.Booking().ApproveSplitAsync(b.Id,f.Opponent.Id);await f.Booking().ApproveSplitAsync(b.Id,f.Opponent.Id);Assert.Equal(950,f.Opponent.CreditBalanceUnits);}
 [Fact]public async Task External_debit_is_idempotent_and_fractional_exact(){await using var f=new Fixture();await f.Init();var c=new CreditService(f.Db,f.Clock);await c.ExternalDebitAsync(f.Member.Id,50,"ext-1","Gate");await c.ExternalDebitAsync(f.Member.Id,50,"ext-1","Gate");Assert.Equal(950,f.Member.CreditBalanceUnits);Assert.Single(await f.Db.CreditTransactions.Where(x=>x.ExternalReference=="ext-1").ToListAsync());}
 [Fact]public async Task Lighting_is_authorised_idempotent_capped_and_reconciled(){await using var f=new Fixture();await f.Init();var b=await f.Booking().BookAsync(new(f.Member.Id,f.Court.Id,f.Clock.Now.AddMinutes(4)));var provider=new MockLightingProvider();var lights=new CourtLightingService(f.Db,provider,f.Options,f.Clock);var first=await lights.TurnOnAsync(b.Id,f.Member.Id);var second=await lights.TurnOnAsync(b.Id,f.Member.Id);Assert.Equal(first.Id,second.Id);Assert.Equal(b.EndsAtUtc,first.ScheduledOffAtUtc);f.Clock.Now=b.EndsAtUtc;await lights.ReconcileAsync();Assert.False(await provider.IsOnAsync(f.Court.Id,default));Assert.Equal(LightingSessionStatus.Off,first.Status);}
 [Fact]public async Task Unrelated_member_cannot_activate_lights(){await using var f=new Fixture();await f.Init();var b=await f.Booking().BookAsync(new(f.Member.Id,f.Court.Id,f.Clock.Now.AddMinutes(4)));var lights=new CourtLightingService(f.Db,new MockLightingProvider(),f.Options,f.Clock);var stranger=Guid.NewGuid();var e=await Assert.ThrowsAsync<ClubRuleException>(()=>lights.TurnOnAsync(b.Id,stranger));Assert.Equal("FORBIDDEN",e.Code);}
}
